spring.application.name=Entreprise_Apps_Mohamed.Azahaf-1
spring.datasource.url=[uw-db-source-url-met-db-server-poort-en-db-naam]
spring.datasource.username=[db-username]
spring.datasource.password=[db-wachtwoord]

#smtp configuratie
spring.mail.host=uw-mail-server
spring.mail.port=0
spring.mail.username=[uw-emailadres]
spring.mail.password=[uw-emailwachtwoord]
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop